name: Spring Boot CI

on:
  push:
    branches:
      - main
      - feature/*  # Trigger workflow on feature branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Ubuntu runner for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Run tests with Maven (Optional, if you want to execute tests separately)
      - name: Run tests with Maven
        run: mvn test
